import 'dotenv/config'; import express from 'express'; import helmet from 'helmet'; import {rateLimit} from 'express-rate-limit';
import {searchPexelsPhotos,searchPexelsVideos} from './providers/pexels.js'; import {searchUnsplashPhotos,trackUnsplash} from './providers/unsplash.js'; import {searchPixabayPhotos} from './providers/pixabay.js'; import {scoreAsset} from './lib/score.js';
const app=express(); app.use(helmet()); app.use(express.json({limit:'32kb'})); app.use(rateLimit({windowMs:60000,limit:60}));
const env=process.env; const timeout=Number(env.REQUEST_TIMEOUT_MS||12000);
app.use((req,res,next)=>{ if(!env.GATEWAY_API_KEY)return next(); const a=req.get('authorization')||''; if(a!==`Bearer ${env.GATEWAY_API_KEY}`)return res.status(401).json({error:'Unauthorized'}); next(); });
async function fetchJson(url,opts={}){ const c=new AbortController(); const t=setTimeout(()=>c.abort(),timeout); try{const r=await fetch(url,{...opts,signal:c.signal}); const data=await r.json().catch(()=>({})); if(!r.ok){const e=new Error(`Provider ${r.status}`); e.status=r.status; e.details=data; throw e;} return {data,headers:r.headers};}finally{clearTimeout(t)}}
function validateStockUrl(url){ const u=new URL(url); const allowed=['images.pexels.com','images.unsplash.com','cdn.pixabay.com','pixabay.com']; if(u.protocol!=='https:')throw Object.assign(new Error('Only HTTPS asset URLs are allowed'),{status:400}); if(!allowed.some(h=>u.hostname===h||u.hostname.endsWith(`.${h}`)))throw Object.assign(new Error('Asset URL host is not an approved stock provider'),{status:400}); return u.toString();}
async function fetchAsset(url){ const safeUrl=validateStockUrl(url); const c=new AbortController(); const t=setTimeout(()=>c.abort(),timeout); try{const r=await fetch(safeUrl,{signal:c.signal,headers:{'User-Agent':'Poster API Gateway v4'}}); if(!r.ok)throw Object.assign(new Error(`Asset download ${r.status}`),{status:r.status}); const type=r.headers.get('content-type')||'application/octet-stream'; if(!type.startsWith('image/'))throw Object.assign(new Error('Downloaded asset is not an image'),{status:415}); const max=Number(env.MAX_DOWNLOAD_BYTES||12000000); const ab=await r.arrayBuffer(); if(ab.byteLength>max)throw Object.assign(new Error('Downloaded asset exceeds MAX_DOWNLOAD_BYTES'),{status:413}); return {buffer:Buffer.from(ab),contentType:type};}finally{clearTimeout(t)}}
function escapeXml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function dataUri(asset){return `data:${asset.contentType};base64,${asset.buffer.toString('base64')}`;}
const enabled={pexels:()=>!!env.PEXELS_API_KEY,unsplash:()=>!!env.UNSPLASH_ACCESS_KEY,pixabay:()=>!!env.PIXABAY_API_KEY};
app.get('/v1/health',(req,res)=>res.json({ok:true,version:'4.0.0',providers:Object.fromEntries(Object.entries(enabled).map(([k,v])=>[k,v()]))}));
app.get('/v1/assets/photos/search',async(req,res)=>{const q={query:String(req.query.query||'').trim(),providers:String(req.query.providers||'pexels,unsplash,pixabay').split(','),orientation:req.query.orientation,color:req.query.color,page:Number(req.query.page||1),limit:Math.min(Number(req.query.limit||8),20)}; if(!q.query||q.query.length>200)return res.status(400).json({error:'Invalid query'}); const out=[],warnings=[],used=[]; for(const p of q.providers){try{if(!enabled[p]?.()){warnings.push(`${p} not configured`);continue;} let a=p==='pexels'?await searchPexelsPhotos(q,env,fetchJson):p==='unsplash'?await searchUnsplashPhotos(q,env,fetchJson):await searchPixabayPhotos(q,env,fetchJson); a=Array.isArray(a)?a:a.results; out.push(...a);used.push(p);}catch(e){warnings.push(`${p}: ${e.message}`)}} const seen=new Set(); const results=out.filter(x=>{const k=x.source_page||`${x.provider}:${x.id}`;if(seen.has(k))return false;seen.add(k);return true}).map(x=>({...x,score:scoreAsset(x,q)})).sort((a,b)=>b.score-a.score).slice(0,q.limit); res.json({query:q.query,providers_used:used,warnings,results});});
app.get('/v1/assets/videos/search',async(req,res)=>{const q={query:String(req.query.query||'').trim(),orientation:req.query.orientation,page:Number(req.query.page||1),limit:Math.min(Number(req.query.limit||8),20)};if(!q.query)return res.status(400).json({error:'query required'});const results=enabled.pexels()?await searchPexelsVideos(q,env,fetchJson):[];res.json({query:q.query,providers_used:results.length?['pexels']:[],warnings:results.length?[]:['pexels not configured'],results});});
app.get('/v1/assets/icons/search',async(req,res)=>{const q=encodeURIComponent(String(req.query.query||''));const r=await fetchJson(`https://api.iconify.design/search?query=${q}&limit=${Math.min(Number(req.query.limit||12),30)}`);res.json({query:req.query.query,providers_used:['iconify'],results:(r.data.icons||[]).map(id=>({provider:'iconify',id,source_page:`https://icon-sets.iconify.design/${id.split(':')[0]}/${id.split(':')[1]}/`,preview_url:`https://api.iconify.design/${id.replace(':','/')}.svg`,asset_url:`https://api.iconify.design/${id.replace(':','/')}.svg`,license_name:'Varies by icon set'}))});});
app.get('/v1/assets/fonts/search',async(req,res)=>{if(!env.GOOGLE_FONTS_API_KEY)return res.status(503).json({error:'Google Fonts not configured'});const r=await fetchJson(`https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity&key=${encodeURIComponent(env.GOOGLE_FONTS_API_KEY)}`);const terms=String(req.query.query||'').toLowerCase().split(/\s+/);const results=(r.data.items||[]).filter(f=>terms.some(t=>f.family.toLowerCase().includes(t))||!terms[0]).slice(0,Math.min(Number(req.query.limit||10),20)).map(f=>({provider:'google-fonts',id:f.family,description:f.family,source_page:`https://fonts.google.com/specimen/${encodeURIComponent(f.family)}`,variants:f.variants,subsets:f.subsets,license_name:'See Google Fonts specimen/license'}));res.json({query:req.query.query,providers_used:['google-fonts'],results});});
app.post('/v1/assets/photos/:provider/:id/select',async(req,res)=>{if(req.params.provider==='unsplash'){if(!req.body?.download_location)return res.status(400).json({error:'download_location required'});const data=await trackUnsplash(req.body.download_location,env,fetchJson);return res.json({selected:true,tracked:true,provider:'unsplash',download_url:data.url});}res.json({selected:true,tracked:false,provider:req.params.provider,id:req.params.id});});
app.post('/v1/assets/photos/select-download',async(req,res)=>{const {provider,id,asset_url,download_location,source_page,creator_name,attribution,license_name,license_url,return_file_data=false}=req.body||{}; if(!['pexels','unsplash','pixabay'].includes(provider))return res.status(400).json({error:'provider must be pexels, unsplash, or pixabay'}); let url=asset_url; let tracked=false; if(provider==='unsplash'){if(!download_location)return res.status(400).json({error:'download_location required for Unsplash'}); const data=await trackUnsplash(download_location,env,fetchJson); url=data.url||url; tracked=true;} if(!url)return res.status(400).json({error:'asset_url required'}); validateStockUrl(url); const base={provider,id,tracked,download_url:url,source_page,creator_name,attribution,license_name,license_url}; if(!return_file_data)return res.json(base); const asset=await fetchAsset(url); res.json({...base,content_type:asset.contentType,file_name:`${provider}-${id||'stock'}.${asset.contentType.includes('png')?'png':'jpg'}`,file_data:dataUri(asset)});});
app.post('/v1/posters/render-from-stock',async(req,res)=>{const {background_image_url,background_file_data,canvas={},text_layers=[],overlays=[],attribution}=req.body||{}; const width=Math.min(Math.max(Number(canvas.width||1080),320),4096); const height=Math.min(Math.max(Number(canvas.height||1350),320),4096); let image=background_file_data; if(!image&&background_image_url)image=validateStockUrl(background_image_url); if(!image)return res.status(400).json({error:'background_image_url or background_file_data required'}); const overlaySvg=overlays.map(o=>`<rect x="${Number(o.x||0)}" y="${Number(o.y||0)}" width="${Number(o.width||width)}" height="${Number(o.height||height)}" fill="${escapeXml(o.color||'#000000')}" opacity="${Math.max(0,Math.min(Number(o.opacity??0.35),1))}"/>`).join(''); const textSvg=text_layers.slice(0,20).map(t=>`<text x="${Number(t.x||0)}" y="${Number(t.y||0)}" fill="${escapeXml(t.color||'#ffffff')}" font-family="${escapeXml(t.font_family||'Arial, sans-serif')}" font-size="${Math.min(Math.max(Number(t.font_size||48),8),240)}" font-weight="${escapeXml(t.font_weight||'700')}" text-anchor="${escapeXml(t.text_anchor||'start')}">${escapeXml(t.text||'')}</text>`).join(''); const credit=attribution?`<text x="32" y="${height-32}" fill="#ffffff" opacity=".72" font-family="Arial, sans-serif" font-size="18">${escapeXml(attribution)}</text>`:''; const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><image href="${escapeXml(image)}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid slice"/>${overlaySvg}${textSvg}${credit}</svg>`; res.json({output_content_type:'image/svg+xml',output_file_name:'poster-from-stock.svg',output_data:`data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`,width,height});});
app.post('/v1/images/generate',(req,res)=>res.status(501).json({error:'Configure your preferred image provider in this endpoint'}));
app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message,details:e.details})); app.listen(Number(env.PORT||3000),()=>console.log('Poster API v4 listening'));
